# Generated by Django 3.1.3 on 2020-11-06 03:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=32, null=True)),
                ('public_token', models.CharField(default='', max_length=64)),
                ('access_token', models.CharField(default='', max_length=64)),
                ('item_id', models.CharField(default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=32, null=True)),
                ('item_id', models.CharField(max_length=64, unique=True)),
                ('available_products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('auth', 'Authentication'), ('identity', 'Identity'), ('balance', 'Balance'), ('credit_details', 'Credit Details'), ('transactions', 'Transactions'), ('item', 'item'), ('income', 'income'), ('assets', 'assets'), ('holdings', 'holdings'), ('investments', 'investments'), ('liabilities', 'liabilities')], max_length=32, null=True), blank=True, default=list, null=True, size=10)),
                ('billed_products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('auth', 'Authentication'), ('identity', 'Identity'), ('balance', 'Balance'), ('credit_details', 'Credit Details'), ('transactions', 'Transactions'), ('item', 'item'), ('income', 'income'), ('assets', 'assets'), ('holdings', 'holdings'), ('investments', 'investments'), ('liabilities', 'liabilities')], max_length=32, null=True), blank=True, default=list, null=True, size=10)),
                ('institution_id', models.CharField(blank=True, max_length=32, null=True)),
                ('webhook', models.URLField(blank=True, null=True)),
                ('relink_status', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=32, null=True)),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('balances', models.JSONField(blank=True, null=True)),
                ('mask', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('official_name', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(choices=[('investment', 'Investment'), ('credit', 'Credit Card'), ('depository', 'Depository Account'), ('loan', 'Loan Account'), ('other', 'Non specified account type')], max_length=32)),
                ('subtype', models.CharField(max_length=256)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_data.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
