# Generated by Django 3.1.3 on 2020-11-06 08:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('webhook_type', models.CharField(blank=True, choices=[('TRANSACTIONS', 'Transactions')], default='TRANSACTIONS', max_length=20, null=True)),
                ('webhook_code', models.CharField(blank=True, choices=[('INITIAL_UPDATE', 'Initial Update'), ('HISTORICAL_UPDATE', 'Historical Update'), ('DEFAULT_UPDATE', 'Default Update'), ('TRANSACTIONS_REMOVED', 'Transactions removed')], max_length=20, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('new_transactions', models.IntegerField(blank=True, null=True)),
                ('removed_transactions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64, null=True), blank=True, null=True, size=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_data.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=32, null=True)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('account_owner', models.CharField(max_length=256, null=True)),
                ('pending_transaction_id', models.CharField(max_length=64, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('payment_channel', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_processor', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_meta', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=24, null=True)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, default=list, null=True, size=10)),
                ('iso_currency_code', models.CharField(blank=True, max_length=16, null=True)),
                ('unofficial_currency_code', models.CharField(blank=True, max_length=16, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=64)),
                ('transaction_code', models.CharField(blank=True, choices=[('adjustment', 'Adjustment'), ('atm', 'Atm'), ('bank', 'Bank'), ('charge', 'Charge'), ('bill payment', 'Bill payment'), ('cash', 'Cash'), ('cashback', 'Cashback'), ('cheque', 'Cheque'), ('direct debit', 'Direct'), ('interest', 'Interest'), ('purchase', 'Purchase'), ('standing order', 'Standing Order'), ('transfer', 'Transfer')], max_length=32, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_data.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_data.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
