# Generated by Django 3.1.3 on 2020-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_data', '0002_transaction_transactionwebhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionwebhook',
            name='item',
        ),
        migrations.AddField(
            model_name='transactionwebhook',
            name='item_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=64),
        ),
    ]
